name: Test ign-cmake
on: [push]

jobs:
  build_and_test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-18.04]
    steps:
      - uses: mjcarroll/action-setup-ign@releases/v1
      - uses: actions/checkout@v1
      - name: Build
        run: |
          mkdir build
          cd build
          cmake ..
          make
      - name: Test
        run: |
          cd build
          make test
